CREATE TABLE Animals(
   ID             INTEGER  NOT NULL PRIMARY KEY 
  ,Name           VARCHAR(11)
  ,BirthDate      DATETIME  NOT NULL
  ,AnimalType     VARCHAR(3) NOT NULL
  ,Sex            VARCHAR(13) NOT NULL
  ,Breed          VARCHAR(36) NOT NULL
  ,Description    VARCHAR(19) NOT NULL
  ,AdoptionStatus VARCHAR(6) NOT NULL
);
UPDATE Animals SET ID = 1,Name = 'Summer',BirthDate = '10/12/2015 12:15',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Labrador Retriever Mix',Description = 'Red/White',AdoptionStatus = 'Foster' WHERE ID= 1;
UPDATE Animals SET ID = 2,Name = 'Cheyenne',BirthDate = '7/26/2014 17:59',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'German Shepherd/Siberian Husky',Description = 'Black/Tan',AdoptionStatus = 'Foster' WHERE ID= 2;
UPDATE Animals SET ID = 3,Name = 'Gus',BirthDate = '1/13/2016 12:20',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Foster' WHERE ID= 3;
UPDATE Animals SET ID = 4,Name = 'Pongo',BirthDate = '12/28/2013 18:12',AnimalType = 'Dog',Sex = 'Intact Male',Breed = 'Collie Smooth Mix',Description = 'Tricolor',AdoptionStatus = 'Adopt' WHERE ID= 4;
UPDATE Animals SET ID = 5,Name = 'Skooter',BirthDate = '9/24/2015 17:59',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Miniature Poodle Mix',Description = 'White',AdoptionStatus = 'Adopt' WHERE ID= 5;
UPDATE Animals SET ID = 6,Name = 'Beau',BirthDate = '6/23/2015 11:17',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Beagle Mix',Description = 'Brown/White',AdoptionStatus = 'Adopt' WHERE ID= 6;
UPDATE Animals SET ID = 7,Name = 'Bobo',BirthDate = '3/12/2014 9:45',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Medium Hair Mix',Description = 'Brown Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 7;
UPDATE Animals SET ID = 8,Name = 'Abby',BirthDate = '6/25/2014 8:27',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Foster' WHERE ID= 8;
UPDATE Animals SET ID = 9,Name = 'Ruby Grace',BirthDate = '11/12/2014 18:05',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Cairn Terrier',Description = 'Black/Cream',AdoptionStatus = 'Foster' WHERE ID= 9;
UPDATE Animals SET ID = 10,Name = 'Ruby',BirthDate = '4/7/2014 17:41',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pit Bull Mix',Description = 'Brown/White',AdoptionStatus = 'Foster' WHERE ID= 10;
UPDATE Animals SET ID = 11,Name = 'Marlee',BirthDate = '1/1/2014 17:03',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Labrador Retriever Mix',Description = 'White/Black',AdoptionStatus = 'Adopt' WHERE ID= 11;
UPDATE Animals SET ID = 12,Name = 'Lala',BirthDate = '9/19/2014 15:40',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Pit Bull Mix',Description = 'Blue/White',AdoptionStatus = 'Adopt' WHERE ID= 12;
UPDATE Animals SET ID = 13,Name = 'Chloe',BirthDate = '1/25/2015 15:13',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pit Bull Mix',Description = 'Brown Brindle',AdoptionStatus = 'Foster' WHERE ID= 13;
UPDATE Animals SET ID = 14,Name = 'Joe',BirthDate = '9/22/2015 18:17',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Miniature Poodle Mix',Description = 'White',AdoptionStatus = 'Foster' WHERE ID= 14;
UPDATE Animals SET ID = 15,Name = 'Duffy',BirthDate = '7/20/2014 19:24',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Flat Coat Retriever/German Shepherd',Description = 'Black/Brown',AdoptionStatus = 'Foster' WHERE ID= 15;
UPDATE Animals SET ID = 16,Name = 'Jiggy',BirthDate = '3/26/2014 18:33',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pointer/Labrador Retriever',Description = 'White',AdoptionStatus = 'Adopt' WHERE ID= 16;
UPDATE Animals SET ID = 17,Name = 'Ghengis',BirthDate = '5/29/2015 17:04',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Doberman Pinsch Mix',Description = 'Black/Tan',AdoptionStatus = 'Adopt' WHERE ID= 17;
UPDATE Animals SET ID = 18,Name = 'Decker',BirthDate = '1/19/2016 19:31',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'English Bulldog',Description = 'White/Tricolor',AdoptionStatus = 'Adopt' WHERE ID= 18;
UPDATE Animals SET ID = 19,Name = 'Freckles',BirthDate = '6/16/2014 12:49',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Torbie',AdoptionStatus = 'Adopt' WHERE ID= 19;
UPDATE Animals SET ID = 20,Name = 'Bucky',BirthDate = '2/11/2014 19:27',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Torbie',AdoptionStatus = 'Adopt' WHERE ID= 20;
UPDATE Animals SET ID = 21,Name = 'Pumpkin',BirthDate = '11/14/2014 19:32',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 21;
UPDATE Animals SET ID = 22,Name = 'Jank',BirthDate = '5/4/2015 13:46',AnimalType = 'Cat',Sex = 'Unknown',Breed = 'Domestic Shorthair Mix',Description = 'Black',AdoptionStatus = 'Adopt' WHERE ID= 22;
UPDATE Animals SET ID = 23,Name = 'Pluto',BirthDate = '6/7/2014 14:14',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Norwich Terrier Mix',Description = 'White/Tan',AdoptionStatus = 'Foster' WHERE ID= 23;
UPDATE Animals SET ID = 24,Name = 'Adrian',BirthDate = '7/20/2014 15:37',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 24;
UPDATE Animals SET ID = 25,Name = 'Portia',BirthDate = '10/26/2013 16:23',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Black Mouth Cur/Boxer',Description = 'Tan',AdoptionStatus = 'Adopt' WHERE ID= 25;
UPDATE Animals SET ID = 26,Name = 'Ethan',BirthDate = '12/29/2014 13:10',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 26;
UPDATE Animals SET ID = 27,Name = 'Lucy',BirthDate = '7/23/2015 16:18',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Medium Hair Mix',Description = 'Black Smoke',AdoptionStatus = 'Adopt' WHERE ID= 27;
UPDATE Animals SET ID = 28,Name = 'Edward',BirthDate = '3/19/2015 8:33',AnimalType = 'Dog',Sex = 'Intact Male',Breed = 'Norwich Terrier Mix',Description = 'Brown',AdoptionStatus = 'Adopt' WHERE ID= 28;
UPDATE Animals SET ID = 29,Name = 'Jack',BirthDate = '10/9/2014 17:22',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever Mix',Description = 'Black/White',AdoptionStatus = 'Adopt' WHERE ID= 29;
UPDATE Animals SET ID = 30,Name = 'Knight',BirthDate = '5/13/2014 17:03',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever Mix',Description = 'Black',AdoptionStatus = 'Adopt' WHERE ID= 30;
UPDATE Animals SET ID = 31,Name = 'Harry',BirthDate = '5/5/2015 15:13',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pomeranian Mix',Description = 'Black/White',AdoptionStatus = 'Foster' WHERE ID= 31;
UPDATE Animals SET ID = 32,Name = 'Indiana',BirthDate = '1/31/2015 11:36',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Chihuahua Shorthair/Dachshund',Description = 'Black/White',AdoptionStatus = 'Foster' WHERE ID= 32;
UPDATE Animals SET ID = 33,Name = 'Nickie',BirthDate = '11/14/2013 15:02',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Medium Hair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Foster' WHERE ID= 33;
UPDATE Animals SET ID = 34,Name = 'Nord',BirthDate = '4/25/2015 18:05',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby/White',AdoptionStatus = 'Foster' WHERE ID= 34;
UPDATE Animals SET ID = 35,Name = 'Alice',BirthDate = '8/2/2015 12:59',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 35;
UPDATE Animals SET ID = 36,Name = 'Nick',BirthDate = '3/24/2014 12:15',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Australian Cattle Dog Mix',Description = 'Red Merle/White',AdoptionStatus = 'Foster' WHERE ID= 36;
UPDATE Animals SET ID = 37,Name = 'Joseph',BirthDate = '11/3/2015 9:00',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 37;
UPDATE Animals SET ID = 38,Name = 'Pongo',BirthDate = '12/26/2015 17:30',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever Mix',Description = 'Black/White',AdoptionStatus = 'Adopt' WHERE ID= 38;
UPDATE Animals SET ID = 39,Name = 'Brittney',BirthDate = '12/30/2015 15:57',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Miniature Poodle/Lhasa Apso',Description = 'Tan',AdoptionStatus = 'Adopt' WHERE ID= 39;
UPDATE Animals SET ID = 40,Name = 'Bagel',BirthDate = '2/6/2014 14:19',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Border Terrier Mix',Description = 'Gold',AdoptionStatus = 'Foster' WHERE ID= 40;
UPDATE Animals SET ID = 41,Name = 'Chaney',BirthDate = '10/31/2015 16:02',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Beagle Mix',Description = 'Tricolor',AdoptionStatus = 'Foster' WHERE ID= 41;
UPDATE Animals SET ID = 42,Name = 'Baguette',BirthDate = '5/13/2014 13:23',AnimalType = 'Cat',Sex = 'Intact Male',Breed = 'Domestic Shorthair Mix',Description = 'Orange Tabby',AdoptionStatus = 'Adopt' WHERE ID= 42;
UPDATE Animals SET ID = 43,Name = 'Angie',BirthDate = '12/22/2013 12:37',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Black/White',AdoptionStatus = 'Adopt' WHERE ID= 43;
UPDATE Animals SET ID = 44,Name = 'Sandy',BirthDate = '10/16/2013 11:50',AnimalType = 'Cat',Sex = 'Intact Male',Breed = 'Domestic Medium Hair Mix',Description = 'Blue',AdoptionStatus = 'Adopt' WHERE ID= 44;
UPDATE Animals SET ID = 45,Name = 'Toast',BirthDate = '4/10/2014 12:13',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Blue Tabby',AdoptionStatus = 'Foster' WHERE ID= 45;
UPDATE Animals SET ID = 46,Name = 'Tinker',BirthDate = '2/24/2014 14:57',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Whippet/Rat Terrier',Description = 'Tricolor',AdoptionStatus = 'Foster' WHERE ID= 46;
UPDATE Animals SET ID = 47,Name = 'Sophia',BirthDate = '3/7/2014 12:42',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Orange Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 47;
UPDATE Animals SET ID = 48,Name = 'Frisco',BirthDate = '11/14/2015 15:52',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Pit Bull Mix',Description = 'Brown Brindle/White',AdoptionStatus = 'Adopt' WHERE ID= 48;
UPDATE Animals SET ID = 49,Name = 'Chica',BirthDate = '7/27/2015 13:06',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Japanese Chin Mix',Description = 'White/Black',AdoptionStatus = 'Adopt' WHERE ID= 49;
UPDATE Animals SET ID = 50,Name = 'Ire',BirthDate = '5/8/2015 15:01',AnimalType = 'Dog',Sex = 'Intact Male',Breed = 'Labrador Retriever/Doberman Pinsch',Description = 'Chocolate',AdoptionStatus = 'Adopt' WHERE ID= 50;
UPDATE Animals SET ID = 51,Name = 'Comet',BirthDate = '7/29/2015 13:31',AnimalType = 'Cat',Sex = 'Intact Male',Breed = 'Domestic Longhair Mix',Description = 'Blue Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 51;
UPDATE Animals SET ID = 52,Name = 'Booch',BirthDate = '7/27/2014 11:26',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Black/Tan Hound Mix',Description = 'Black/Brown',AdoptionStatus = 'Adopt' WHERE ID= 52;
UPDATE Animals SET ID = 53,Name = 'Kodiak',BirthDate = '5/30/2015 16:41',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 53;
UPDATE Animals SET ID = 54,Name = 'Periwinkle',BirthDate = '10/7/2014 16:08',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Blue/White',AdoptionStatus = 'Adopt' WHERE ID= 54;
UPDATE Animals SET ID = 56,Name = 'Stella',BirthDate = '10/12/2015 16:50',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 56;
UPDATE Animals SET ID = 57,Name = 'Tizoc',BirthDate = '1/27/2016 17:51',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Catahoula Mix',Description = 'Brown/Tan',AdoptionStatus = 'Adopt' WHERE ID= 57;
UPDATE Animals SET ID = 58,Name = NULL,BirthDate = '6/30/2015 12:22',AnimalType = 'Cat',Sex = 'Unknown',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 58;
UPDATE Animals SET ID = 59,Name = NULL,BirthDate = '4/18/2015 9:00',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 59;
UPDATE Animals SET ID = 60,Name = 'Charlie',BirthDate = '9/9/2015 13:55',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Plott Hound/Labrador Retriever',Description = 'Black',AdoptionStatus = 'Adopt' WHERE ID= 60;
UPDATE Animals SET ID = 61,Name = NULL,BirthDate = '7/23/2014 19:05',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever/American Foxhound',Description = 'White/Red',AdoptionStatus = 'Foster' WHERE ID= 61;
UPDATE Animals SET ID = 62,Name = 'Yellow',BirthDate = '11/18/2014 11:55',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Pit Bull Mix',Description = 'Tan/White',AdoptionStatus = 'Foster' WHERE ID= 62;
UPDATE Animals SET ID = 63,Name = 'Cooper',BirthDate = '3/5/2014 11:49',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Bombay Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 63;
UPDATE Animals SET ID = 64,Name = NULL,BirthDate = '6/17/2015 12:27',AnimalType = 'Cat',Sex = 'Intact Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 64;
UPDATE Animals SET ID = 65,Name = NULL,BirthDate = '8/20/2014 9:00',AnimalType = 'Cat',Sex = 'Intact Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Foster' WHERE ID= 65;
UPDATE Animals SET ID = 66,Name = 'Bella',BirthDate = '10/18/2014 18:06',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Chihuahua Shorthair Mix',Description = 'Black/Brown',AdoptionStatus = 'Adopt' WHERE ID= 66;
UPDATE Animals SET ID = 67,Name = 'Tiernee',BirthDate = '11/22/2015 18:15',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 67;
UPDATE Animals SET ID = 68,Name = 'Peanut',BirthDate = '6/26/2014 12:11',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Chihuahua Shorthair Mix',Description = 'Black/Tan',AdoptionStatus = 'Foster' WHERE ID= 68;
UPDATE Animals SET ID = 69,Name = 'Boris',BirthDate = '6/4/2014 17:09',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Boxer Mix',Description = 'Blue/White',AdoptionStatus = 'Foster' WHERE ID= 69;
UPDATE Animals SET ID = 70,Name = NULL,BirthDate = '8/24/2014 9:00',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Adopt' WHERE ID= 70;
UPDATE Animals SET ID = 71,Name = NULL,BirthDate = '1/20/2016 13:29',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Anatol Shepherd/Labrador Retriever',Description = 'White/Tan',AdoptionStatus = 'Foster' WHERE ID= 71;
UPDATE Animals SET ID = 72,Name = 'Olive',BirthDate = '2/21/2015 17:58',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Cardigan Welsh Corgi Mix',Description = 'Brown/White',AdoptionStatus = 'Adopt' WHERE ID= 72;
UPDATE Animals SET ID = 73,Name = NULL,BirthDate = '6/13/2014 10:51',AnimalType = 'Cat',Sex = 'Unknown',Breed = 'Domestic Shorthair Mix',Description = 'Gray/Black',AdoptionStatus = 'Adopt' WHERE ID= 73;
UPDATE Animals SET ID = 74,Name = 'Rocky',BirthDate = '10/9/2013 12:48',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Chihuahua Shorthair Mix',Description = 'Brown',AdoptionStatus = 'Foster' WHERE ID= 74;
UPDATE Animals SET ID = 75,Name = NULL,BirthDate = '8/21/2015 16:59',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Medium Hair Mix',Description = 'Orange Tabby/White',AdoptionStatus = 'Foster' WHERE ID= 75;
UPDATE Animals SET ID = 76,Name = 'Calamity',BirthDate = '8/30/2015 11:06',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Longhair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 76;
UPDATE Animals SET ID = 77,Name = 'Daisy',BirthDate = '11/16/2013 12:21',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Medium Hair Mix',Description = 'Tortie',AdoptionStatus = 'Foster' WHERE ID= 77;
UPDATE Animals SET ID = 78,Name = NULL,BirthDate = '6/17/2015 9:00',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 78;
UPDATE Animals SET ID = 79,Name = 'Oreo',BirthDate = '8/4/2014 14:13',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pug/Italian Greyhound',Description = 'Chocolate',AdoptionStatus = 'Foster' WHERE ID= 79;
UPDATE Animals SET ID = 80,Name = 'Zeus',BirthDate = '8/20/2014 17:18',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair',Description = 'Brown Tabby/White',AdoptionStatus = 'Foster' WHERE ID= 80;
UPDATE Animals SET ID = 83,Name = 'King',BirthDate = '2/15/2015 17:30',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Blue Lacy Mix',Description = 'Blue/White',AdoptionStatus = 'Adopt' WHERE ID= 83;
UPDATE Animals SET ID = 85,Name = 'Bandit',BirthDate = '10/23/2014 19:12',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'English Foxhound Mix',Description = 'Tricolor',AdoptionStatus = 'Adopt' WHERE ID= 85;
UPDATE Animals SET ID = 87,Name = 'Abby',BirthDate = '3/14/2014 18:39',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Pit Bull Mix',Description = 'Brown/White',AdoptionStatus = 'Foster' WHERE ID= 87;
UPDATE Animals SET ID = 88,Name = 'French Fry',BirthDate = '4/2/2015 15:25',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pit Bull Mix',Description = 'Black Brindle',AdoptionStatus = 'Adopt' WHERE ID= 88;
UPDATE Animals SET ID = 90,Name = 'Lulu',BirthDate = '12/1/2013 14:02',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Siamese Mix',Description = 'Calico Point',AdoptionStatus = 'Adopt' WHERE ID= 90;
UPDATE Animals SET ID = 93,Name = 'Azul',BirthDate = '6/24/2015 14:59',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Longhair Mix',Description = 'Blue',AdoptionStatus = 'Foster' WHERE ID= 93;
UPDATE Animals SET ID = 94,Name = 'Kiko',BirthDate = '5/24/2014 15:30',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Chihuahua Shorthair Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 94;
UPDATE Animals SET ID = 96,Name = 'Marty',BirthDate = '6/1/2014 19:19',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Jack Russell Terrier Mix',Description = 'Tricolor',AdoptionStatus = 'Adopt' WHERE ID= 96;
UPDATE Animals SET ID = 97,Name = 'Sonora',BirthDate = '10/25/2015 15:05',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Labrador Retriever Mix',Description = 'White',AdoptionStatus = 'Adopt' WHERE ID= 97;
UPDATE Animals SET ID = 99,Name = 'Patches',BirthDate = '10/2/2013 16:48',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Medium Hair Mix',Description = 'Calico',AdoptionStatus = 'Adopt' WHERE ID= 99;
UPDATE Animals SET ID = 100,Name = 'Sophie',BirthDate = '10/21/2014 16:23',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Beagle Mix',Description = 'Sable',AdoptionStatus = 'Foster' WHERE ID= 100;
UPDATE Animals SET ID = 101,Name = 'Tyrus',BirthDate = '5/5/2014 15:11',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 101;
UPDATE Animals SET ID = 102,Name = 'Daisy',BirthDate = '7/18/2015 19:44',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Black',AdoptionStatus = 'Adopt' WHERE ID= 102;
UPDATE Animals SET ID = 103,Name = 'Chester',BirthDate = '12/7/2013 11:56',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Great Pyrenees',Description = 'White',AdoptionStatus = 'Adopt' WHERE ID= 103;
UPDATE Animals SET ID = 104,Name = 'Skippy',BirthDate = '12/4/2015 13:40',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever Mix',Description = 'Yellow/White',AdoptionStatus = 'Foster' WHERE ID= 104;
UPDATE Animals SET ID = 105,Name = 'Baby',BirthDate = '1/20/2014 12:21',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Torbie',AdoptionStatus = 'Foster' WHERE ID= 105;
UPDATE Animals SET ID = 106,Name = 'Huck',BirthDate = '1/5/2014 15:24',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 106;
UPDATE Animals SET ID = 107,Name = 'Moondog',BirthDate = '9/1/2014 17:37',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Miniature Poodle/Cairn Terrier',Description = 'White',AdoptionStatus = 'Foster' WHERE ID= 107;
UPDATE Animals SET ID = 108,Name = 'Augie',BirthDate = '12/19/2015 15:41',AnimalType = 'Dog',Sex = 'Intact Female',Breed = 'Yorkshire Terrier Mix',Description = 'Brown/Black',AdoptionStatus = 'Foster' WHERE ID= 108;
UPDATE Animals SET ID = 109,Name = 'Ivy',BirthDate = '9/23/2014 18:19',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Siamese',Description = 'Tortie Point',AdoptionStatus = 'Foster' WHERE ID= 109;
UPDATE Animals SET ID = 110,Name = 'Remy',BirthDate = '12/24/2014 11:58',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Russian Blue Mix',Description = 'Blue',AdoptionStatus = 'Foster' WHERE ID= 110;
UPDATE Animals SET ID = 111,Name = 'Che',BirthDate = '11/15/2015 16:08',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Beagle Mix',Description = 'Brown/Black',AdoptionStatus = 'Adopt' WHERE ID= 111;
UPDATE Animals SET ID = 112,Name = 'Chico',BirthDate = '4/19/2015 15:33',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Pit Bull Mix',Description = 'Brown Brindle/White',AdoptionStatus = 'Adopt' WHERE ID= 112;
UPDATE Animals SET ID = 113,Name = 'Romen',BirthDate = '1/26/2016 12:13',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Cocker Spaniel/Shetland Sheepdog',Description = 'Tan',AdoptionStatus = 'Foster' WHERE ID= 113;
UPDATE Animals SET ID = 114,Name = 'London',BirthDate = '11/24/2015 13:45',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'German Shepherd Mix',Description = 'White',AdoptionStatus = 'Foster' WHERE ID= 114;
UPDATE Animals SET ID = 116,Name = 'Loco',BirthDate = '8/30/2015 12:03',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Chihuahua Shorthair Mix',Description = 'Red',AdoptionStatus = 'Foster' WHERE ID= 116;
UPDATE Animals SET ID = 117,Name = 'Goldie',BirthDate = '2/14/2015 17:13',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Australian Kelpie Mix',Description = 'Tan',AdoptionStatus = 'Foster' WHERE ID= 117;
UPDATE Animals SET ID = 118,Name = 'Chunk',BirthDate = '7/23/2014 13:16',AnimalType = 'Dog',Sex = 'Intact Male',Breed = 'Boxer',Description = 'Brown Brindle/White',AdoptionStatus = 'Adopt' WHERE ID= 118;
UPDATE Animals SET ID = 119,Name = 'Randee',BirthDate = '10/31/2013 11:43',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Pekingese',Description = 'Yellow/Tan',AdoptionStatus = 'Foster' WHERE ID= 119;
UPDATE Animals SET ID = 121,Name = 'Louisa',BirthDate = '6/24/2015 12:23',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Tortie',AdoptionStatus = 'Foster' WHERE ID= 121;
UPDATE Animals SET ID = 122,Name = 'Newton',BirthDate = '3/1/2014 15:17',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Medium Hair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 122;
UPDATE Animals SET ID = 123,Name = 'Huckleberry',BirthDate = '5/25/2015 17:23',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Blue',AdoptionStatus = 'Adopt' WHERE ID= 123;
UPDATE Animals SET ID = 126,Name = 'Sammy',BirthDate = '4/25/2015 17:54',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Labrador Retriever/German Shepherd',Description = 'Sable/White',AdoptionStatus = 'Foster' WHERE ID= 126;
UPDATE Animals SET ID = 128,Name = 'Phoebe',BirthDate = '1/17/2015 11:13',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 128;
UPDATE Animals SET ID = 129,Name = 'Rooster',BirthDate = '7/1/2014 18:59',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Orange Tabby',AdoptionStatus = 'Adopt' WHERE ID= 129;
UPDATE Animals SET ID = 130,Name = 'Nigel',BirthDate = '10/13/2014 19:02',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Blue',AdoptionStatus = 'Foster' WHERE ID= 130;
UPDATE Animals SET ID = 131,Name = 'Dylan',BirthDate = '4/13/2015 17:22',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Australian Shepherd Mix',Description = 'Tricolor',AdoptionStatus = 'Foster' WHERE ID= 131;
UPDATE Animals SET ID = 132,Name = 'Amos',BirthDate = '7/20/2015 18:20',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby',AdoptionStatus = 'Adopt' WHERE ID= 132;
UPDATE Animals SET ID = 134,Name = 'Pearl',BirthDate = '5/28/2015 11:24',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Chihuahua Shorthair',Description = 'Tricolor',AdoptionStatus = 'Adopt' WHERE ID= 134;
UPDATE Animals SET ID = 135,Name = 'Sierra',BirthDate = '12/13/2014 13:50',AnimalType = 'Cat',Sex = 'Spayed Female',Breed = 'Domestic Shorthair Mix',Description = 'Blue Tabby',AdoptionStatus = 'Foster' WHERE ID= 135;
UPDATE Animals SET ID = 136,Name = 'Rajah',BirthDate = '11/5/2014 18:33',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Siberian Husky Mix',Description = 'Red/White',AdoptionStatus = 'Foster' WHERE ID= 136;
UPDATE Animals SET ID = 137,Name = 'Timmy',BirthDate = '4/13/2014 13:14',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Domestic Shorthair Mix',Description = 'Blue Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 137;
UPDATE Animals SET ID = 139,Name = 'Priscilla',BirthDate = '5/2/2015 13:00',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Labrador Retriever/Basset Hound',Description = 'Brown/White',AdoptionStatus = 'Adopt' WHERE ID= 139;
UPDATE Animals SET ID = 140,Name = 'Jimmy',BirthDate = '12/27/2015 0:00',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Pharaoh Hound Mix',Description = 'Brown/White',AdoptionStatus = 'Foster' WHERE ID= 140;
UPDATE Animals SET ID = 141,Name = 'Wanda',BirthDate = '10/30/2015 16:31',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Chihuahua Shorthair Mix',Description = 'Brown',AdoptionStatus = 'Adopt' WHERE ID= 141;
UPDATE Animals SET ID = 142,Name = 'Wynnie',BirthDate = '8/25/2015 15:03',AnimalType = 'Cat',Sex = 'Intact Female',Breed = 'Domestic Shorthair Mix',Description = 'Brown Tabby/White',AdoptionStatus = 'Adopt' WHERE ID= 142;
UPDATE Animals SET ID = 143,Name = 'Riley',BirthDate = '7/23/2014 13:07',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Catahoula Mix',Description = 'Brown Merle',AdoptionStatus = 'Foster' WHERE ID= 143;
UPDATE Animals SET ID = 144,Name = 'Jessica',BirthDate = '7/6/2015 14:55',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Shetland Sheepdog Mix',Description = 'Black',AdoptionStatus = 'Foster' WHERE ID= 144;
UPDATE Animals SET ID = 145,Name = 'Diesel',BirthDate = '2/12/2015 11:01',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pit Bull Mix',Description = 'Brown Brindle/White',AdoptionStatus = 'Adopt' WHERE ID= 145;
UPDATE Animals SET ID = 146,Name = 'Molly',BirthDate = '10/27/2015 13:30',AnimalType = 'Dog',Sex = 'Spayed Female',Breed = 'Pit Bull Mix',Description = 'Black Brindle/White',AdoptionStatus = 'Foster' WHERE ID= 146;
UPDATE Animals SET ID = 147,Name = 'Toby',BirthDate = '8/12/2014 9:28',AnimalType = 'Cat',Sex = 'Neutered Male',Breed = 'Snowshoe Mix',Description = 'Lilac Point',AdoptionStatus = 'Foster' WHERE ID= 147;
UPDATE Animals SET ID = 148,Name = 'Maximillion',BirthDate = '11/12/2014 18:37',AnimalType = 'Dog',Sex = 'Neutered Male',Breed = 'Miniature Pinscher Mix',Description = 'Black/Brown',AdoptionStatus = 'Adopt' WHERE ID= 148;
