CREATE TABLE Animals(
   ID             INTEGER NOT NULL PRIMARY KEY 
  ,Name           VARCHAR(11)
  ,BirthDate      DATE NOT NULL
  ,AnimalType     VARCHAR(3) NOT NULL
  ,Sex            VARCHAR(13) NOT NULL
  ,Breed          VARCHAR(36) NOT NULL
  ,Description    VARCHAR(19) NOT NULL
  ,AdoptionStatus VARCHAR(6) NOT NULL
);
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (1,'Summer','2015-10-12','Dog','Intact Female','Labrador Retriever Mix','Red/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (2,'Cheyenne','2014-07-26','Dog','Spayed Female','German Shepherd/Siberian 
Husky','Black/Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (3,'Gus','2016-01-13','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (4,'Pongo','2013-12-28','Dog','Intact Male','Collie Smooth Mix','Tricolor','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (5,'Skooter','2015-09-24','Dog','Neutered Male','Miniature Poodle Mix','White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (6,'Beau','2015-06-23','Dog','Neutered Male','Beagle Mix','Brown/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (7,'Bobo','2014-03-12','Cat','Neutered Male','Domestic Medium Hair Mix','Brown Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (8,'Abby','2014-06-25','Cat','Spayed Female','Domestic Shorthair Mix','Brown Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (9,'Ruby Grace','2014-11-12','Dog','Spayed Female','Cairn Terrier','Black/Cream','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (10,'Ruby','2014-04-07','Dog','Spayed Female','Pit Bull Mix','Brown/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (11,'Marlee','2014-01-01','Dog','Spayed Female','Labrador Retriever Mix','White/Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (12,'Lala','2014-09-19','Dog','Intact Female','Pit Bull Mix','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (13,'Chloe','2015-01-25','Dog','Spayed Female','Pit Bull Mix','Brown Brindle','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (14,'Joe','2015-09-22','Dog','Neutered Male','Miniature Poodle Mix','White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (15,'Duffy','2014-07-20','Dog','Neutered Male','Flat Coat Retriever/German 
Shepherd','Black/Brown','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (16,'Jiggy','2014-03-26','Dog','Spayed Female','Pointer/Labrador Retriever','White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (17,'Ghengis','2015-05-29','Dog','Neutered Male','Doberman Pinsch Mix','Black/Tan','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (18,'Decker','2016-01-19','Dog','Neutered Male','English Bulldog','White/Tricolor','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (19,'Freckles','2014-06-16','Cat','Spayed Female','Domestic Shorthair Mix','Torbie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (20,'Bucky','2014-02-11','Cat','Intact Female','Domestic Shorthair Mix','Torbie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (21,'Pumpkin','2014-11-14','Cat','Spayed Female','Domestic Shorthair Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (22,'Jank','2015-05-04','Cat','Unknown','Domestic Shorthair Mix','Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (23,'Pluto','2014-06-07','Dog','Neutered Male','Norwich Terrier Mix','White/Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (24,'Adrian','2014-07-20','Cat','Intact Female','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (25,'Portia','2013-10-26','Dog','Spayed Female','Black Mouth Cur/Boxer','Tan','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (26,'Ethan','2014-12-29','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (27,'Lucy','2015-07-23','Cat','Spayed Female','Domestic Medium Hair Mix','Black Smoke','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (28,'Edward','2015-03-19','Dog','Intact Male','Norwich Terrier Mix','Brown','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (29,'Jack','2014-10-09','Dog','Neutered Male','Labrador Retriever Mix','Black/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (30,'Knight','2014-05-13','Dog','Neutered Male','Labrador Retriever Mix','Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (31,'Harry','2015-05-05','Dog','Spayed Female','Pomeranian Mix','Black/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (32,'Indiana','2015-01-31','Dog','Spayed Female','Chihuahua Shorthair/Dachshund','Black/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (33,'Nickie','2013-11-14','Cat','Neutered Male','Domestic Medium Hair Mix','Brown Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (34,'Nord','2015-04-25','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (35,'Alice','2015-08-02','Cat','Intact Female','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (36,'Nick','2014-03-24','Dog','Neutered Male','Australian Cattle Dog Mix','Red Merle/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (37,'Joseph','2015-11-03','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (38,'Pongo','2015-12-26','Dog','Neutered Male','Labrador Retriever Mix','Black/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (39,'Brittney','2015-12-30','Dog','Spayed Female','Miniature Poodle/Lhasa Apso','Tan','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (40,'Bagel','2014-02-06','Dog','Neutered Male','Border Terrier Mix','Gold','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (41,'Chaney','2015-10-31','Dog','Intact Female','Beagle Mix','Tricolor','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (42,'Baguette','2014-05-13','Cat','Intact Male','Domestic Shorthair Mix','Orange Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (43,'Angie','2013-12-22','Cat','Spayed Female','Domestic Shorthair Mix','Black/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (44,'Sandy','2013-10-16','Cat','Intact Male','Domestic Medium Hair Mix','Blue','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (45,'Toast','2014-04-10','Cat','Neutered Male','Domestic Shorthair Mix','Blue Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (46,'Tinker','2014-02-24','Dog','Spayed Female','Whippet/Rat Terrier','Tricolor','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (47,'Sophia','2014-03-07','Cat','Spayed Female','Domestic Shorthair Mix','Orange Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (48,'Frisco','2015-11-14','Dog','Neutered Male','Pit Bull Mix','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (49,'Chica','2015-07-27','Dog','Spayed Female','Japanese Chin Mix','White/Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (50,'Ire','2015-05-08','Dog','Intact Male','Labrador Retriever/Doberman Pinsch','Chocolate','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (51,'Comet','2015-07-29','Cat','Intact Male','Domestic Longhair Mix','Blue 
Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (52,'Booch','2014-07-27','Dog','Spayed Female','Black/Tan Hound Mix','Black/Brown','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (53,'Kodiak','2015-05-30','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (54,'Periwinkle','2014-10-07','Cat','Intact Female','Domestic Shorthair Mix','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (55,'Perry','2014-10-12','Cat','Spayed Female','Domestic Shorthair Mix','Black/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (56,'Stella','2015-10-12','Cat','Spayed Female','Domestic Shorthair Mix','Brown Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (57,'Tizoc','2016-01-27','Dog','Neutered Male','Catahoula Mix','Brown/Tan','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (58,'Fido','2015-06-30','Cat','Unknown','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (59,'Fido','2015-04-18','Cat','Intact Female','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (60,'Charlie','2015-09-09','Dog','Neutered Male','Plott Hound/Labrador Retriever','Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (61,'Fido','2014-07-23','Dog','Neutered Male','Labrador Retriever/American 
Foxhound','White/Red','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (62,'Yellow','2014-11-18','Dog','Neutered Male','Pit Bull Mix','Tan/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (63,'Cooper','2014-03-05','Cat','Neutered Male','Bombay Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (64,'Fido','2015-06-17','Cat','Intact Male','Domestic Shorthair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (65,'Fido','2014-08-20','Cat','Intact Male','Domestic Shorthair Mix','Brown Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (66,'Bella','2014-10-18','Dog','Spayed Female','Chihuahua Shorthair Mix','Black/Brown','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (67,'Tiernee','2015-11-22','Cat','Spayed Female','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (68,'Peanut','2014-06-26','Dog','Intact Female','Chihuahua Shorthair Mix','Black/Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (69,'Boris','2014-06-04','Dog','Neutered Male','Boxer Mix','Blue/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (70,'Fido','2014-08-24','Cat','Intact Female','Domestic Shorthair Mix','Tortie','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (71,'Fido','2016-01-20','Dog','Intact Female','Anatol Shepherd/Labrador Retriever','White/Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (72,'Olive','2015-02-21','Dog','Spayed Female','Cardigan Welsh Corgi Mix','Brown/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (73,'Fido','2014-06-13','Cat','Unknown','Domestic Shorthair Mix','Gray/Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (74,'Rocky','2013-10-09','Dog','Neutered Male','Chihuahua Shorthair Mix','Brown','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (75,'Fido','2015-08-21','Cat','Intact Female','Domestic Medium Hair Mix','Orange Tabby/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (76,'Calamity','2015-08-30','Cat','Intact Female','Domestic Longhair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (77,'Daisy','2013-11-16','Cat','Spayed Female','Domestic Medium Hair Mix','Tortie','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (78,'Fido','2015-06-17','Cat','Neutered Male','Domestic Shorthair Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (79,'Oreo','2014-08-04','Dog','Spayed Female','Pug/Italian Greyhound','Chocolate','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (80,'Zeus','2014-08-20','Cat','Neutered Male','Domestic Shorthair','Brown Tabby/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (81,'Winkle','2014-01-07','Dog','Neutered Male','Domestic Shorthair Mix','Blue/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (82,'Periwinkle','2014-10-07','Dog','Intact Female','Pug/Italian Greyhound','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (83,'King','2015-02-15','Dog','Neutered Male','Blue Lacy Mix','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (84,'Periwinkle','2001-12-07','Cat','Intact Female','Domestic Shorthair Mix','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (85,'Bandit','2014-10-23','Dog','Neutered Male','English Foxhound Mix','Tricolor','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (86,'Yugi','2014-10-07','Cat','Neutered Male','English Foxhound Mix','Blue/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (87,'Abby','2014-03-14','Dog','Intact Female','Pit Bull Mix','Brown/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (88,'French Fry','2015-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (89,'Fry Fry','2012-04-12','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (90,'Lulu','2013-12-01','Cat','Spayed Female','Siamese Mix','Calico Point','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (91,'French Salt','2015-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (92,'Pizza','2020-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (93,'Azul','2015-06-24','Cat','Spayed Female','Domestic Longhair Mix','Blue','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (94,'Kiko','2014-05-24','Dog','Neutered Male','Chihuahua Shorthair Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (95,'Sausage','2015-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (96,'Marty','2014-06-01','Dog','Neutered Male','Jack Russell Terrier Mix','Tricolor','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (97,'Sonora','2015-10-25','Dog','Spayed Female','Labrador Retriever Mix','White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (98,'Zuko','2015-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (99,'Patches','2013-10-02','Cat','Intact Female','Domestic Medium Hair Mix','Calico','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (100,'Sophie','2014-10-21','Dog','Spayed Female','Beagle Mix','Sable','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (101,'Tyrus','2014-05-05','Cat','Neutered Male','Domestic Shorthair Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (102,'Daisy','2015-07-18','Cat','Spayed Female','Domestic Shorthair Mix','Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (103,'Chester','2013-12-07','Dog','Neutered Male','Great Pyrenees','White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (104,'Skippy','2015-12-04','Dog','Neutered Male','Labrador Retriever Mix','Yellow/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (105,'Baby','2014-01-20','Cat','Spayed Female','Domestic Shorthair Mix','Torbie','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (106,'Huck','2014-01-05','Dog','Neutered Male','Labrador Retriever Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (107,'Moondog','2014-09-01','Dog','Neutered Male','Miniature Poodle/Cairn Terrier','White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (108,'Augie','2015-12-19','Dog','Intact Female','Yorkshire Terrier Mix','Brown/Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (109,'Ivy','2014-09-23','Cat','Spayed Female','Siamese','Tortie Point','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (110,'Remy','2014-12-24','Cat','Spayed Female','Russian Blue Mix','Blue','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (111,'Che','2015-11-15','Dog','Spayed Female','Beagle Mix','Brown/Black','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (112,'Chico','2015-04-19','Dog','Neutered Male','Pit Bull Mix','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (113,'Romen','2016-01-26','Dog','Neutered Male','Cocker Spaniel/Shetland Sheepdog','Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (114,'London','2015-11-24','Dog','Neutered Male','German Shepherd Mix','White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (115,'Thai','2015-04-02','Dog','Spayed Female','Pit Bull Mix','Black Brindle','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (116,'Loco','2015-08-30','Dog','Neutered Male','Chihuahua Shorthair Mix','Red','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (117,'Goldie','2015-02-14','Dog','Spayed Female','Australian Kelpie Mix','Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (118,'Chunk','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (119,'Randee','2013-10-31','Dog','Neutered Male','Pekingese','Yellow/Tan','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (120,'Chunkyy','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (121,'Louisa','2015-06-24','Cat','Spayed Female','Domestic Shorthair Mix','Tortie','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (122,'Newton','2014-03-01','Cat','Neutered Male','Domestic Medium Hair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (123,'Huckleberry','2015-05-25','Cat','Neutered Male','Domestic Shorthair Mix','Blue','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (124,'Chonker','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (125,'Bubba','2014-07-23','Dog','Neutered Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (126,'Sammy','2015-04-25','Dog','Neutered Male','Labrador Retriever/German 
Shepherd','Sable/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (127,'Chuck Norris','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (128,'Phoebe','2015-01-17','Cat','Spayed Female','Domestic Shorthair Mix','Brown Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (129,'Rooster','2014-07-01','Cat','Neutered Male','Domestic Shorthair Mix','Orange Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (130,'Nigel','2014-10-13','Cat','Neutered Male','Domestic Shorthair Mix','Blue','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (131,'Dylan','2015-04-13','Dog','Neutered Male','Australian Shepherd Mix','Tricolor','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (132,'Amos','2015-07-20','Cat','Neutered Male','Domestic Shorthair Mix','Brown Tabby','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (133,'Chunkah','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (134,'Pearl','2015-05-28','Dog','Spayed Female','Chihuahua Shorthair','Tricolor','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (135,'Sierra','2014-12-13','Cat','Spayed Female','Domestic Shorthair Mix','Blue Tabby','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (136,'Rajah','2014-11-05','Dog','Spayed Female','Siberian Husky Mix','Red/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (137,'Timmy','2014-04-13','Cat','Neutered Male','Domestic Shorthair Mix','Blue Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (138,'Parth','2014-07-23','Dog','Intact Male','Boxer','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (139,'Priscilla','2015-05-02','Dog','Spayed Female','Labrador Retriever/Basset Hound','Brown/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (140,'Jimmy','2015-12-27','Dog','Neutered Male','Pharaoh Hound Mix','Brown/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (141,'Wanda','2015-10-30','Dog','Spayed Female','Chihuahua Shorthair Mix','Brown','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (142,'Wynnie','2015-08-25','Cat','Intact Female','Domestic Shorthair Mix','Brown Tabby/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (143,'Riley','2014-07-23','Dog','Spayed Female','Catahoula Mix','Brown Merle','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (144,'Jessica','2015-07-06','Dog','Spayed Female','Shetland Sheepdog Mix','Black','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (145,'Diesel','2015-02-12','Dog','Spayed Female','Pit Bull Mix','Brown Brindle/White','Adopt');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (146,'Molly','2015-10-27','Dog','Spayed Female','Pit Bull Mix','Black Brindle/White','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (147,'Toby','2014-08-12','Cat','Neutered Male','Snowshoe Mix','Lilac Point','Foster');
INSERT INTO Animals(ID,Name,BirthDate,AnimalType,Sex,Breed,Description,AdoptionStatus) VALUES (148,'Maximillion','2014-11-12','Dog','Neutered Male','Miniature Pinscher Mix','Black/Brown','Adopt');
